// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUZ4k6G0cOVasnexP0S6vuJd9vFDcFYSc',
    appId: '1:97147344656:web:52b1f3a1f51520da5f7795',
    messagingSenderId: '97147344656',
    projectId: 'jetkiz-mobile',
    authDomain: 'jetkiz-mobile.firebaseapp.com',
    storageBucket: 'jetkiz-mobile.firebasestorage.app',
    measurementId: 'G-8NWR8NSRFV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzeYsBwMaIT3QKBPh70Q17jBk4EUTiRgM',
    appId: '1:97147344656:android:09888a326ced5c1e5f7795',
    messagingSenderId: '97147344656',
    projectId: 'jetkiz-mobile',
    storageBucket: 'jetkiz-mobile.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzMILm99MIxSGAkmFv4R2U2HPsFwitZZM',
    appId: '1:97147344656:ios:af1d91deb1420a8f5f7795',
    messagingSenderId: '97147344656',
    projectId: 'jetkiz-mobile',
    storageBucket: 'jetkiz-mobile.firebasestorage.app',
    iosBundleId: 'com.example.jetkizMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzMILm99MIxSGAkmFv4R2U2HPsFwitZZM',
    appId: '1:97147344656:ios:af1d91deb1420a8f5f7795',
    messagingSenderId: '97147344656',
    projectId: 'jetkiz-mobile',
    storageBucket: 'jetkiz-mobile.firebasestorage.app',
    iosBundleId: 'com.example.jetkizMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUZ4k6G0cOVasnexP0S6vuJd9vFDcFYSc',
    appId: '1:97147344656:web:0fc1055293aa71085f7795',
    messagingSenderId: '97147344656',
    projectId: 'jetkiz-mobile',
    authDomain: 'jetkiz-mobile.firebaseapp.com',
    storageBucket: 'jetkiz-mobile.firebasestorage.app',
    measurementId: 'G-2010DH6XBB',
  );
}
